### ISSUE TITLE
Remove class Genre, GenreTest and delete extra attributes and methods

### ISSUE THREAD

**Issue by ezedepetris** [nmaguirre/riocuartobandasderock#37]
delete the class Genre, GenreTest
delete Attributes and Methods on class Band
fix Tests of Band after delete attributes, methods and class Genre

**Comment by ezedepetris** [comment]
Resolved on the next rev [d40548e], [cf23ef5] and [06aecac]

**Comment by orevitnoonairam** [comment]
You forgot to delete the imports on classes BandTest and SongTest

**Comment by ezedepetris** [comment]
on class BandTest i remove the import in this rev [3e2d48f], tanks, but on the class SongTest it's not my responsability
